package com.exam.entities;

import javax.persistence.*;

// This class represents a user in the system. A user could be an admin, student, or instructor.
@Entity // Marks this class as a JPA entity, meaning it is mapped to a table in the database.
@Table(name = "users") // Specifies the table name ("users") to store user data in the database.
public class User {

    // Primary key for the User entity. It's automatically generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    private int id;

    // The username of the user. This will typically be used for logging in.
    private String username;

    // The password of the user (should be stored securely in a real application).
    private String password;

    // The role of the user. It can be "admin", "student", or "instructor".
    private String role;

    // Getters and Setters for each field in the User entity.

    public int getId() {
        return id; // Returns the ID of the user.
    }

    public void setId(int id) {
        this.id = id; // Sets the ID of the user.
    }

    public String getUsername() {
        return username; // Returns the username of the user.
    }

    public void setUsername(String username) {
        this.username = username; // Sets the username of the user.
    }

    public String getPassword() {
        return password; // Returns the password of the user.
    }

    public void setPassword(String password) {
        this.password = password; // Sets the password of the user.
    }

    public String getRole() {
        return role; // Returns the role of the user.
    }

    public void setRole(String role) {
        this.role = role; // Sets the role of the user.
    }

    // Constructor to initialize the User with a username and role.
    public User(String username, String role) {
        this.username = username;
        this.role = role;
    }
}
